name: 'Tag Release'

on:
  push:
    branches:
      - master
      - 'release-*'
    paths:
      - version.go

jobs:
  tag-release:
    if: ${{ github.repository == 'kaidotdev/kops' }}
    runs-on: ubuntu-20.04

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - run: /usr/bin/git config --global user.email actions@github.com
      - run: /usr/bin/git config --global user.name 'GitHub Actions Release Tagger'
      - run: hack/tag-release.sh
